bifrost:
  big-bang:
    type: public
    genesis-id: b_CScnuBgGUigEPZgXthMP6LYoDpx34dVk1XwY7TLKfpVD
    source-path: https://raw.githubusercontent.com/Topl/Genesis/main/toplnet
  p2p:
    network-properties:
      expected-slots-per-block: 10
